Repository ultralytics/pre-commit, pull requests merged in 2025-01, with the labels that each got.

#21 Apply `ruff==0.9.0` formatting
  capitalize_comments.py
Labels: enhancement, devops

#22 Standardize license headers in Python files
  capitalize_comments.py
Labels: documentation

#23 Update capitalize_comments.py
  capitalize_comments.py
Labels: documentation

#24 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
  .pre-commit-hooks.yaml
  pyproject.toml
Labels: documentation, devops
